/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Northeastern.SummerCampManagement.View;

/**
 *
 * @author jalan
 */
public class CampMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public CampMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        campSplitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        adminButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        camperButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        rightPanel = new javax.swing.JPanel();
        adminDashboard = new javax.swing.JPanel();
        dashboardCampLabel = new javax.swing.JLabel();
        dashboardStaffLabel = new javax.swing.JLabel();
        studentTextLabel = new javax.swing.JLabel();
        staffTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboardStaffLabel1 = new javax.swing.JLabel();
        staffTextLabel1 = new javax.swing.JLabel();
        registrationReportPanel = new javax.swing.JPanel();
        RegistrationReportTextLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        feedbackPanel = new javax.swing.JPanel();
        parentCrudtextLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        campRegButton = new javax.swing.JButton();
        campAdmindashboardButton = new javax.swing.JButton();
        campFeedbackButton = new javax.swing.JButton();
        staffPanel = new javax.swing.JPanel();
        staffSplitPane = new javax.swing.JSplitPane();
        rightStaffPanel = new javax.swing.JPanel();
        staffDashboard = new javax.swing.JPanel();
        parentDashboardLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        staffActivityPanel = new javax.swing.JPanel();
        activityTitle = new javax.swing.JLabel();
        activityNameTextLabel = new javax.swing.JLabel();
        activityAgeTextfield = new javax.swing.JTextField();
        activityDescriptionLabel = new javax.swing.JLabel();
        activityCreateButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        activityDescriptionTextarea = new javax.swing.JTextArea();
        activityCategoryLabel = new javax.swing.JLabel();
        activityCategoryCombo = new javax.swing.JComboBox<>();
        activityAgeGroupLabel = new javax.swing.JLabel();
        activityNameTextfield1 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        staffSchedulePanel = new javax.swing.JPanel();
        staffScheduleLabel = new javax.swing.JLabel();
        scheduleActivityLabel = new javax.swing.JLabel();
        activityDateLabel = new javax.swing.JLabel();
        activityStartTime = new javax.swing.JLabel();
        activityEndTimeLabel = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        activityStartTimeText = new javax.swing.JTextField();
        activityEndTimeText = new javax.swing.JTextField();
        activityLocationLabel = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        staffScheduleSubmitButton = new javax.swing.JButton();
        dietryPreferencePanel = new javax.swing.JPanel();
        dietaryPrefLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        leftStaffPanel = new javax.swing.JPanel();
        staffActivityButton = new javax.swing.JButton();
        staffDashboardButton = new javax.swing.JButton();
        staffSchedulesButton = new javax.swing.JButton();
        staffDietButton = new javax.swing.JButton();
        camperPanel = new javax.swing.JPanel();
        camperSplitPane = new javax.swing.JSplitPane();
        rightCamperPanel = new javax.swing.JPanel();
        camperDashboard = new javax.swing.JPanel();
        camperDashboardPanel = new javax.swing.JPanel();
        camperUpcomingActivityDashboardLabel = new javax.swing.JLabel();
        camperscheduleImageLabel = new javax.swing.JLabel();
        camperDashboardLabel = new javax.swing.JLabel();
        camperActivityPanel = new javax.swing.JPanel();
        camperActivityLabel = new javax.swing.JLabel();
        firstNameProfileLabel = new javax.swing.JLabel();
        lastNameStudentProfileLabel = new javax.swing.JLabel();
        emailStudentProfileLabel = new javax.swing.JLabel();
        contactNumberStudentProfileLabel = new javax.swing.JLabel();
        addressStudentProfileLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastNameStudentTextLabel = new javax.swing.JLabel();
        studentFirstNameTextLabel = new javax.swing.JLabel();
        AddressStudentTextLabel = new javax.swing.JLabel();
        UserNameStudentTextLabel = new javax.swing.JLabel();
        lastNameStudentText = new javax.swing.JLabel();
        ContactNumberStudentText = new javax.swing.JLabel();
        AgeStudentText = new javax.swing.JLabel();
        camperSchedulePanel = new javax.swing.JPanel();
        schoolReportLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AttendancestudentText = new javax.swing.JLabel();
        gradeStudentText = new javax.swing.JLabel();
        camperDietPanel = new javax.swing.JPanel();
        campReportLabel1 = new javax.swing.JLabel();
        studentMealPrefLabel1 = new javax.swing.JLabel();
        viewCampReportButton1 = new javax.swing.JButton();
        campRegistrationUserName = new javax.swing.JLabel();
        campRegistrationPassword = new javax.swing.JLabel();
        studentMealPrefTextField2 = new javax.swing.JTextField();
        studentMealPrefTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        campRegistrationBeverageLabel = new javax.swing.JLabel();
        campRegistrationFoodLabel = new javax.swing.JLabel();
        campRegistrationAllergiesLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        campRegistrationMedCondition = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        leftCamperPanel = new javax.swing.JPanel();
        camperActivityButton = new javax.swing.JButton();
        camperDashboardButton = new javax.swing.JButton();
        camperDietButton = new javax.swing.JButton();
        camperScheduleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campSplitPane.setDividerLocation(70);
        campSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        adminButton.setText("Admin");

        staffButton.setText("Staff");
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });

        camperButton.setText("Camper");

        logoutButton.setForeground(new java.awt.Color(255, 51, 0));
        logoutButton.setText("X");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(adminButton)
                .addGap(105, 105, 105)
                .addComponent(staffButton)
                .addGap(101, 101, 101)
                .addComponent(camperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(23, 23, 23))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        campSplitPane.setTopComponent(topPanel);

        bottomPanel.setLayout(new java.awt.CardLayout());

        adminPanel.setPreferredSize(new java.awt.Dimension(700, 595));

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setPreferredSize(new java.awt.Dimension(700, 595));

        rightPanel.setPreferredSize(new java.awt.Dimension(599, 595));
        rightPanel.setLayout(new java.awt.CardLayout());

        dashboardCampLabel.setText("No. Of Campers");

        dashboardStaffLabel.setText("No. Of Staff");

        studentTextLabel.setText("number here");

        staffTextLabel.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DASHBOARD");

        dashboardStaffLabel1.setText("No. Of Activities");

        staffTextLabel1.setText("jLabel1");

        javax.swing.GroupLayout adminDashboardLayout = new javax.swing.GroupLayout(adminDashboard);
        adminDashboard.setLayout(adminDashboardLayout);
        adminDashboardLayout.setHorizontalGroup(
            adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashboardLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardCampLabel)
                    .addComponent(dashboardStaffLabel))
                .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashboardLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(adminDashboardLayout.createSequentialGroup()
                                .addComponent(studentTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(dashboardStaffLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(staffTextLabel1))))
                    .addGroup(adminDashboardLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(staffTextLabel)))
                .addGap(56, 56, 56))
        );
        adminDashboardLayout.setVerticalGroup(
            adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardLayout.createSequentialGroup()
                .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashboardLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dashboardCampLabel)
                            .addComponent(studentTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardStaffLabel1)
                            .addComponent(staffTextLabel1)))
                    .addGroup(adminDashboardLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addGap(44, 44, 44)
                .addGroup(adminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardStaffLabel)
                    .addComponent(staffTextLabel))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        rightPanel.add(adminDashboard, "card2");

        registrationReportPanel.setPreferredSize(new java.awt.Dimension(599, 595));

        RegistrationReportTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrationReportTextLabel.setText("REGISTRATION REPORT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Registration Date", "Email", "Age", "Address", "Guardian"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(599, 120));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(10);
        }

        javax.swing.GroupLayout registrationReportPanelLayout = new javax.swing.GroupLayout(registrationReportPanel);
        registrationReportPanel.setLayout(registrationReportPanelLayout);
        registrationReportPanelLayout.setHorizontalGroup(
            registrationReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationReportPanelLayout.createSequentialGroup()
                .addGroup(registrationReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationReportPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(RegistrationReportTextLabel))
                    .addGroup(registrationReportPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        registrationReportPanelLayout.setVerticalGroup(
            registrationReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationReportPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(RegistrationReportTextLabel)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(324, 324, 324))
        );

        rightPanel.add(registrationReportPanel, "card3");

        feedbackPanel.setPreferredSize(new java.awt.Dimension(599, 595));

        parentCrudtextLabel.setText("FEEDBACK");

        jLabel9.setText("VISUALIZATION");

        javax.swing.GroupLayout feedbackPanelLayout = new javax.swing.GroupLayout(feedbackPanel);
        feedbackPanel.setLayout(feedbackPanelLayout);
        feedbackPanelLayout.setHorizontalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(parentCrudtextLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        feedbackPanelLayout.setVerticalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentCrudtextLabel)
                .addGap(101, 101, 101)
                .addComponent(jLabel9)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        rightPanel.add(feedbackPanel, "card4");

        jSplitPane2.setRightComponent(rightPanel);

        leftPanel.setBackground(new java.awt.Color(0, 51, 255));

        campRegButton.setText("Registration");

        campAdmindashboardButton.setText("DashBoard");

        campFeedbackButton.setText("Feedback");
        campFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campFeedbackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campAdmindashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campRegButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campFeedbackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(campAdmindashboardButton)
                .addGap(49, 49, 49)
                .addComponent(campRegButton)
                .addGap(55, 55, 55)
                .addComponent(campFeedbackButton)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(leftPanel);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bottomPanel.add(adminPanel, "card2");

        staffPanel.setPreferredSize(new java.awt.Dimension(700, 595));

        staffSplitPane.setDividerLocation(120);
        staffSplitPane.setPreferredSize(new java.awt.Dimension(700, 595));

        rightStaffPanel.setLayout(new java.awt.CardLayout());

        parentDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        parentDashboardLabel.setText("DASHBOARD");

        jLabel1.setText("No. of Campers");

        jLabel3.setText("No. of Activities");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout staffDashboardLayout = new javax.swing.GroupLayout(staffDashboard);
        staffDashboard.setLayout(staffDashboardLayout);
        staffDashboardLayout.setHorizontalGroup(
            staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDashboardLayout.createSequentialGroup()
                .addGroup(staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDashboardLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(parentDashboardLabel))
                    .addGroup(staffDashboardLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(107, 107, 107)
                        .addGroup(staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        staffDashboardLayout.setVerticalGroup(
            staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDashboardLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(parentDashboardLabel)
                .addGap(54, 54, 54)
                .addGroup(staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(53, 53, 53)
                .addGroup(staffDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        rightStaffPanel.add(staffDashboard, "card2");

        staffActivityPanel.setPreferredSize(new java.awt.Dimension(599, 595));

        activityTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activityTitle.setText("ACTIVITIES");

        activityNameTextLabel.setText("Name");

        activityDescriptionLabel.setText("Description");

        activityCreateButton.setText("CREATE ACTIVITY");

        activityDescriptionTextarea.setColumns(20);
        activityDescriptionTextarea.setRows(5);
        jScrollPane2.setViewportView(activityDescriptionTextarea);

        activityCategoryLabel.setText("Category");

        activityCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sports", "Arts and Crafts", "Educational" }));

        activityAgeGroupLabel.setText("Age Group");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Category", "Age Group"
            }
        ));
        jScrollPane8.setViewportView(jTable2);

        javax.swing.GroupLayout staffActivityPanelLayout = new javax.swing.GroupLayout(staffActivityPanel);
        staffActivityPanel.setLayout(staffActivityPanelLayout);
        staffActivityPanelLayout.setHorizontalGroup(
            staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffActivityPanelLayout.createSequentialGroup()
                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffActivityPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(activityTitle))
                    .addGroup(staffActivityPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staffActivityPanelLayout.createSequentialGroup()
                                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activityNameTextLabel)
                                    .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(activityCategoryLabel)
                                        .addComponent(activityDescriptionLabel))
                                    .addGroup(staffActivityPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(activityAgeGroupLabel)))
                                .addGap(36, 36, 36)
                                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activityAgeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activityNameTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activityCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffActivityPanelLayout.createSequentialGroup()
                                .addComponent(activityCreateButton)
                                .addGap(272, 272, 272)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        staffActivityPanelLayout.setVerticalGroup(
            staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffActivityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityTitle)
                .addGap(8, 8, 8)
                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityNameTextLabel)
                    .addComponent(activityNameTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activityDescriptionLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffActivityPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(activityCategoryLabel))
                    .addGroup(staffActivityPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(activityCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(staffActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityAgeGroupLabel)
                    .addComponent(activityAgeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(activityCreateButton)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightStaffPanel.add(staffActivityPanel, "card4");

        staffScheduleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        staffScheduleLabel.setText("STAFF SCHEDULE");

        scheduleActivityLabel.setText("Activity");

        activityDateLabel.setText("Date");

        activityStartTime.setText("Start Time");

        activityEndTimeLabel.setText("End Time");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        activityLocationLabel.setText("Location");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        staffScheduleSubmitButton.setText("SUBMIT");

        javax.swing.GroupLayout staffSchedulePanelLayout = new javax.swing.GroupLayout(staffSchedulePanel);
        staffSchedulePanel.setLayout(staffSchedulePanelLayout);
        staffSchedulePanelLayout.setHorizontalGroup(
            staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(staffScheduleLabel))
                    .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activityDateLabel)
                            .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleActivityLabel)
                                    .addComponent(activityStartTime)
                                    .addComponent(activityEndTimeLabel)
                                    .addComponent(activityLocationLabel))
                                .addGap(62, 62, 62)
                                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(activityEndTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(activityStartTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))))
                    .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(staffScheduleSubmitButton)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        staffSchedulePanelLayout.setVerticalGroup(
            staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSchedulePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(staffScheduleLabel)
                .addGap(23, 23, 23)
                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scheduleActivityLabel)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(activityDateLabel)
                .addGap(32, 32, 32)
                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityStartTime)
                    .addComponent(activityStartTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityEndTimeLabel)
                    .addComponent(activityEndTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activityLocationLabel)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(staffScheduleSubmitButton)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        rightStaffPanel.add(staffSchedulePanel, "card5");

        dietaryPrefLabel.setText("DIETARY PREFERENCES");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Food Preference", "Beverage Preference"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout dietryPreferencePanelLayout = new javax.swing.GroupLayout(dietryPreferencePanel);
        dietryPreferencePanel.setLayout(dietryPreferencePanelLayout);
        dietryPreferencePanelLayout.setHorizontalGroup(
            dietryPreferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dietryPreferencePanelLayout.createSequentialGroup()
                .addGroup(dietryPreferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dietryPreferencePanelLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(dietaryPrefLabel))
                    .addGroup(dietryPreferencePanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        dietryPreferencePanelLayout.setVerticalGroup(
            dietryPreferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dietryPreferencePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(dietaryPrefLabel)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        rightStaffPanel.add(dietryPreferencePanel, "card5");

        staffSplitPane.setRightComponent(rightStaffPanel);

        leftStaffPanel.setBackground(new java.awt.Color(0, 51, 255));
        leftStaffPanel.setPreferredSize(new java.awt.Dimension(120, 595));

        staffActivityButton.setText("Activity");

        staffDashboardButton.setText("DashBoard");
        staffDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDashboardButtonActionPerformed(evt);
            }
        });

        staffSchedulesButton.setText("Schedules");

        staffDietButton.setText("Dietary Preference");
        staffDietButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDietButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftStaffPanelLayout = new javax.swing.GroupLayout(leftStaffPanel);
        leftStaffPanel.setLayout(leftStaffPanelLayout);
        leftStaffPanelLayout.setHorizontalGroup(
            leftStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffDietButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftStaffPanelLayout.createSequentialGroup()
                        .addGroup(leftStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffDashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffSchedulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftStaffPanelLayout.setVerticalGroup(
            leftStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftStaffPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(staffDashboardButton)
                .addGap(41, 41, 41)
                .addComponent(staffActivityButton)
                .addGap(44, 44, 44)
                .addComponent(staffSchedulesButton)
                .addGap(45, 45, 45)
                .addComponent(staffDietButton)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        staffSplitPane.setLeftComponent(leftStaffPanel);

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addComponent(staffSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addComponent(staffSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bottomPanel.add(staffPanel, "card3");

        camperPanel.setPreferredSize(new java.awt.Dimension(700, 595));

        camperSplitPane.setDividerLocation(120);
        camperSplitPane.setPreferredSize(new java.awt.Dimension(700, 595));

        rightCamperPanel.setLayout(new java.awt.CardLayout());

        camperUpcomingActivityDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        camperUpcomingActivityDashboardLabel.setText("UPCOMING ACTIVITIES");

        camperscheduleImageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        camperscheduleImageLabel.setText("SCHEDULE ACTIVITIES IMAGE");

        camperDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        camperDashboardLabel.setText("DASHBOARD");

        javax.swing.GroupLayout camperDashboardPanelLayout = new javax.swing.GroupLayout(camperDashboardPanel);
        camperDashboardPanel.setLayout(camperDashboardPanelLayout);
        camperDashboardPanelLayout.setHorizontalGroup(
            camperDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDashboardPanelLayout.createSequentialGroup()
                .addGroup(camperDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camperDashboardPanelLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(camperUpcomingActivityDashboardLabel))
                    .addGroup(camperDashboardPanelLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(camperscheduleImageLabel))
                    .addGroup(camperDashboardPanelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(camperDashboardLabel)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        camperDashboardPanelLayout.setVerticalGroup(
            camperDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDashboardPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(camperDashboardLabel)
                .addGap(42, 42, 42)
                .addComponent(camperUpcomingActivityDashboardLabel)
                .addGap(18, 18, 18)
                .addComponent(camperscheduleImageLabel)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout camperDashboardLayout = new javax.swing.GroupLayout(camperDashboard);
        camperDashboard.setLayout(camperDashboardLayout);
        camperDashboardLayout.setHorizontalGroup(
            camperDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(camperDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        camperDashboardLayout.setVerticalGroup(
            camperDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(camperDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rightCamperPanel.add(camperDashboard, "card2");

        camperActivityPanel.setPreferredSize(new java.awt.Dimension(599, 595));

        camperActivityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        camperActivityLabel.setText("ACTIVITY");

        firstNameProfileLabel.setText("First Name");

        lastNameStudentProfileLabel.setText("Last Name");

        emailStudentProfileLabel.setText("Email");

        contactNumberStudentProfileLabel.setText("Contact Number");

        addressStudentProfileLabel.setText("Address");

        jLabel4.setText("Age");

        jLabel5.setText("UserName");

        lastNameStudentTextLabel.setText("jLabel7");

        studentFirstNameTextLabel.setText("jLabel8");

        AddressStudentTextLabel.setText("jLabel7");

        UserNameStudentTextLabel.setText("jLabel7");

        lastNameStudentText.setText("jLabel7");

        ContactNumberStudentText.setText("jLabel7");

        AgeStudentText.setText("jLabel7");

        javax.swing.GroupLayout camperActivityPanelLayout = new javax.swing.GroupLayout(camperActivityPanel);
        camperActivityPanel.setLayout(camperActivityPanelLayout);
        camperActivityPanelLayout.setHorizontalGroup(
            camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camperActivityPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameProfileLabel)
                            .addComponent(emailStudentProfileLabel)
                            .addComponent(addressStudentProfileLabel)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameStudentTextLabel)
                            .addComponent(AddressStudentTextLabel)
                            .addComponent(lastNameStudentTextLabel)
                            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentFirstNameTextLabel)))
                        .addGap(198, 198, 198)
                        .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                                .addComponent(contactNumberStudentProfileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(ContactNumberStudentText))
                            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgeStudentText))
                            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                                .addComponent(lastNameStudentProfileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastNameStudentText))))
                    .addGroup(camperActivityPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(camperActivityLabel)))
                .addGap(48, 48, 48))
        );
        camperActivityPanelLayout.setVerticalGroup(
            camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperActivityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camperActivityLabel)
                .addGap(85, 85, 85)
                .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameStudentProfileLabel)
                    .addComponent(firstNameProfileLabel)
                    .addComponent(jLabel6)
                    .addComponent(studentFirstNameTextLabel)
                    .addComponent(lastNameStudentText))
                .addGap(35, 35, 35)
                .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailStudentProfileLabel)
                    .addComponent(contactNumberStudentProfileLabel)
                    .addComponent(lastNameStudentTextLabel)
                    .addComponent(ContactNumberStudentText))
                .addGap(32, 32, 32)
                .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressStudentProfileLabel)
                    .addComponent(jLabel4)
                    .addComponent(AddressStudentTextLabel)
                    .addComponent(AgeStudentText))
                .addGap(33, 33, 33)
                .addGroup(camperActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UserNameStudentTextLabel))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        rightCamperPanel.add(camperActivityPanel, "card4");

        schoolReportLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schoolReportLabel1.setText("SCHOOL REPORT");

        jLabel7.setText("Attendance");

        jLabel8.setText("Overall Grade");

        AttendancestudentText.setText("jLabel9");

        gradeStudentText.setText("jLabel10");

        javax.swing.GroupLayout camperSchedulePanelLayout = new javax.swing.GroupLayout(camperSchedulePanel);
        camperSchedulePanel.setLayout(camperSchedulePanelLayout);
        camperSchedulePanelLayout.setHorizontalGroup(
            camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperSchedulePanelLayout.createSequentialGroup()
                .addGroup(camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camperSchedulePanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(schoolReportLabel1))
                    .addGroup(camperSchedulePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(125, 125, 125)
                        .addGroup(camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AttendancestudentText)
                            .addComponent(gradeStudentText))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        camperSchedulePanelLayout.setVerticalGroup(
            camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperSchedulePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(schoolReportLabel1)
                .addGap(41, 41, 41)
                .addGroup(camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AttendancestudentText))
                .addGap(39, 39, 39)
                .addGroup(camperSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gradeStudentText))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        rightCamperPanel.add(camperSchedulePanel, "card5");

        campReportLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campReportLabel1.setText("CAMP REGISTRATION");

        studentMealPrefLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentMealPrefLabel1.setText("Meal Preference");

        viewCampReportButton1.setText("SUBMIT");
        viewCampReportButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCampReportButton1ActionPerformed(evt);
            }
        });

        campRegistrationUserName.setText("User Name");

        campRegistrationPassword.setText("Password");

        studentMealPrefTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMealPrefTextField2ActionPerformed(evt);
            }
        });

        studentMealPrefTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMealPrefTextField3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juice", "Coke", " " }));

        campRegistrationBeverageLabel.setText("Beverage Preference");

        campRegistrationFoodLabel.setText("Food Preference");

        campRegistrationAllergiesLabel.setText("Allergies");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetarian", "Non Vegetarian", "Vegan" }));

        campRegistrationMedCondition.setText("Medical Conditions");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        javax.swing.GroupLayout camperDietPanelLayout = new javax.swing.GroupLayout(camperDietPanel);
        camperDietPanel.setLayout(camperDietPanelLayout);
        camperDietPanelLayout.setHorizontalGroup(
            camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDietPanelLayout.createSequentialGroup()
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camperDietPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campRegistrationPassword)
                                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(camperDietPanelLayout.createSequentialGroup()
                        .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(camperDietPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(campRegistrationUserName))
                            .addGroup(camperDietPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campRegistrationFoodLabel)
                                    .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campRegistrationBeverageLabel)
                                        .addComponent(studentMealPrefLabel1))
                                    .addComponent(campRegistrationAllergiesLabel)
                                    .addComponent(campRegistrationMedCondition))
                                .addGap(33, 33, 33)
                                .addComponent(studentMealPrefTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)))
                .addComponent(studentMealPrefTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(camperDietPanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(viewCampReportButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, camperDietPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campReportLabel1)
                .addGap(226, 226, 226))
        );
        camperDietPanelLayout.setVerticalGroup(
            camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperDietPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(campReportLabel1)
                .addGap(44, 44, 44)
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentMealPrefTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campRegistrationUserName)
                    .addComponent(campRegistrationPassword)
                    .addComponent(studentMealPrefTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(studentMealPrefLabel1)
                .addGap(14, 14, 14)
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campRegistrationBeverageLabel))
                .addGap(23, 23, 23)
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campRegistrationFoodLabel))
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camperDietPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(campRegistrationAllergiesLabel))
                    .addGroup(camperDietPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(camperDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campRegistrationMedCondition)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(viewCampReportButton1)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        rightCamperPanel.add(camperDietPanel, "card6");

        camperSplitPane.setRightComponent(rightCamperPanel);

        leftCamperPanel.setBackground(new java.awt.Color(0, 51, 255));
        leftCamperPanel.setPreferredSize(new java.awt.Dimension(120, 595));

        camperActivityButton.setText("Activity");
        camperActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camperActivityButtonActionPerformed(evt);
            }
        });

        camperDashboardButton.setText("DashBoard");
        camperDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camperDashboardButtonActionPerformed(evt);
            }
        });

        camperDietButton.setText("Dietary Preference");

        camperScheduleButton.setText("Schedules");

        javax.swing.GroupLayout leftCamperPanelLayout = new javax.swing.GroupLayout(leftCamperPanel);
        leftCamperPanel.setLayout(leftCamperPanelLayout);
        leftCamperPanelLayout.setHorizontalGroup(
            leftCamperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftCamperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftCamperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(camperActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camperDashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camperDietButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camperScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftCamperPanelLayout.setVerticalGroup(
            leftCamperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftCamperPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(camperDashboardButton)
                .addGap(41, 41, 41)
                .addComponent(camperActivityButton)
                .addGap(36, 36, 36)
                .addComponent(camperScheduleButton)
                .addGap(38, 38, 38)
                .addComponent(camperDietButton)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        camperSplitPane.setLeftComponent(leftCamperPanel);

        javax.swing.GroupLayout camperPanelLayout = new javax.swing.GroupLayout(camperPanel);
        camperPanel.setLayout(camperPanelLayout);
        camperPanelLayout.setHorizontalGroup(
            camperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperPanelLayout.createSequentialGroup()
                .addComponent(camperSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        camperPanelLayout.setVerticalGroup(
            camperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camperPanelLayout.createSequentialGroup()
                .addComponent(camperSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bottomPanel.add(camperPanel, "card4");

        campSplitPane.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffButtonActionPerformed

    private void staffDietButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDietButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffDietButtonActionPerformed

    private void staffDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffDashboardButtonActionPerformed

    private void camperDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camperDashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camperDashboardButtonActionPerformed

    private void studentMealPrefTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMealPrefTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMealPrefTextField2ActionPerformed

    private void studentMealPrefTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMealPrefTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMealPrefTextField3ActionPerformed

    private void viewCampReportButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCampReportButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCampReportButton1ActionPerformed

    private void campFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campFeedbackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campFeedbackButtonActionPerformed

    private void camperActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camperActivityButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camperActivityButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressStudentTextLabel;
    private javax.swing.JLabel AgeStudentText;
    private javax.swing.JLabel AttendancestudentText;
    private javax.swing.JLabel ContactNumberStudentText;
    private javax.swing.JLabel RegistrationReportTextLabel;
    private javax.swing.JLabel UserNameStudentTextLabel;
    private javax.swing.JLabel activityAgeGroupLabel;
    private javax.swing.JTextField activityAgeTextfield;
    private javax.swing.JComboBox<String> activityCategoryCombo;
    private javax.swing.JLabel activityCategoryLabel;
    private javax.swing.JButton activityCreateButton;
    private javax.swing.JLabel activityDateLabel;
    private javax.swing.JLabel activityDescriptionLabel;
    private javax.swing.JTextArea activityDescriptionTextarea;
    private javax.swing.JLabel activityEndTimeLabel;
    private javax.swing.JTextField activityEndTimeText;
    private javax.swing.JLabel activityLocationLabel;
    private javax.swing.JLabel activityNameTextLabel;
    private javax.swing.JTextField activityNameTextfield1;
    private javax.swing.JLabel activityStartTime;
    private javax.swing.JTextField activityStartTimeText;
    private javax.swing.JLabel activityTitle;
    private javax.swing.JLabel addressStudentProfileLabel;
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel adminDashboard;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton campAdmindashboardButton;
    private javax.swing.JButton campFeedbackButton;
    private javax.swing.JButton campRegButton;
    private javax.swing.JLabel campRegistrationAllergiesLabel;
    private javax.swing.JLabel campRegistrationBeverageLabel;
    private javax.swing.JLabel campRegistrationFoodLabel;
    private javax.swing.JLabel campRegistrationMedCondition;
    private javax.swing.JLabel campRegistrationPassword;
    private javax.swing.JLabel campRegistrationUserName;
    private javax.swing.JLabel campReportLabel1;
    private javax.swing.JSplitPane campSplitPane;
    private javax.swing.JButton camperActivityButton;
    private javax.swing.JLabel camperActivityLabel;
    private javax.swing.JPanel camperActivityPanel;
    private javax.swing.JButton camperButton;
    private javax.swing.JPanel camperDashboard;
    private javax.swing.JButton camperDashboardButton;
    private javax.swing.JLabel camperDashboardLabel;
    private javax.swing.JPanel camperDashboardPanel;
    private javax.swing.JButton camperDietButton;
    private javax.swing.JPanel camperDietPanel;
    private javax.swing.JPanel camperPanel;
    private javax.swing.JButton camperScheduleButton;
    private javax.swing.JPanel camperSchedulePanel;
    private javax.swing.JSplitPane camperSplitPane;
    private javax.swing.JLabel camperUpcomingActivityDashboardLabel;
    private javax.swing.JLabel camperscheduleImageLabel;
    private javax.swing.JLabel contactNumberStudentProfileLabel;
    private javax.swing.JLabel dashboardCampLabel;
    private javax.swing.JLabel dashboardStaffLabel;
    private javax.swing.JLabel dashboardStaffLabel1;
    private javax.swing.JLabel dietaryPrefLabel;
    private javax.swing.JPanel dietryPreferencePanel;
    private javax.swing.JLabel emailStudentProfileLabel;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JLabel firstNameProfileLabel;
    private javax.swing.JLabel gradeStudentText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lastNameStudentProfileLabel;
    private javax.swing.JLabel lastNameStudentText;
    private javax.swing.JLabel lastNameStudentTextLabel;
    private javax.swing.JPanel leftCamperPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel leftStaffPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel parentCrudtextLabel;
    private javax.swing.JLabel parentDashboardLabel;
    private javax.swing.JPanel registrationReportPanel;
    private javax.swing.JPanel rightCamperPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel rightStaffPanel;
    private javax.swing.JLabel scheduleActivityLabel;
    private javax.swing.JLabel schoolReportLabel1;
    private javax.swing.JButton staffActivityButton;
    private javax.swing.JPanel staffActivityPanel;
    private javax.swing.JButton staffButton;
    private javax.swing.JPanel staffDashboard;
    private javax.swing.JButton staffDashboardButton;
    private javax.swing.JButton staffDietButton;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JLabel staffScheduleLabel;
    private javax.swing.JPanel staffSchedulePanel;
    private javax.swing.JButton staffScheduleSubmitButton;
    private javax.swing.JButton staffSchedulesButton;
    private javax.swing.JSplitPane staffSplitPane;
    private javax.swing.JLabel staffTextLabel;
    private javax.swing.JLabel staffTextLabel1;
    private javax.swing.JLabel studentFirstNameTextLabel;
    private javax.swing.JLabel studentMealPrefLabel1;
    private javax.swing.JTextField studentMealPrefTextField2;
    private javax.swing.JTextField studentMealPrefTextField3;
    private javax.swing.JLabel studentTextLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewCampReportButton1;
    // End of variables declaration//GEN-END:variables
}
